PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX base: <http://www.fake.com/cs7is1-project#>

SELECT ?station ?rainfall
WHERE {
        ?station base:locatedAt ?grid.
        ?station base:locatedAt ?latlong.
        ?latlong base:LocatedIn base:Donegal.
        ?rainRecord base:happenedAt ?grid.
        ?rainRecord base:monthHappened base:May.
        ?rainRecord base:rainfall ?rainfall.
}
#GROUP BY ?county
LIMIT 1
